print('Hola Mundo$') 
print('Maria Rainha e o resto nadinha') 
print('VAI CORINTHIANS')
print ('completamente louco mas um louco consciente')
print('Eu tenho habilidade de fazer historias tristes virarem melodia')
print('Não dá pra fraquejar, quem é guerreiro ligado que guerreiro é assim')